### ISSUE TITLE
Blank writer/director/cast data being incorrectly imported

### ISSUE THREAD

**Issue by Ismelda** [plexinc-agents/LocalMedia.bundle#56] opened 2015-03-11 19:31 UTC
On some files like this one:
http://ismelda.no-ip.org/share/test/Police.Academy.1984.mp4
the embedded metadata while blank seems to actually been used to fill the metadata while gathering it for the movie.

here is an xml example too:
http://ismelda.no-ip.org/share/test/test.xml

**Comment by chriscurtis** [comment] 2015-03-11 21:10
To add some info: I looked at the MP4 in the "MetaX" app, but no values for the writer/director/cast showed up. Likewise, they looked blank in iTunes (well, iTunes only shows Director). So, I think it's something kind of subtle going on, but I don't know what. I'm guessing it might need a tool that can actually look at the raw atom info in the file.

Anyway, since the agent imports the "blank" values for writer/director/cast ("Role" in Plex XML terminology for the latter), the regular metadata agent (e.g. Freebase or TMDB) doesn't bother gathering data since it thinks that the data has already been provided.

**Comment by PlexMovieFan** [comment] 2015-03-12 18:26
I believe the cause is due to a tag in the file.  I found it using Media Player Classic in Windows.  No other program I have sees this tag.  Here is the tag.

iTunMOVI                       : <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>studio</key><string>studio</string><key>cast</key><array><dict><key>name</key><string></string></dict></array><key>directors</key><array><dict><key>name</key><string></string></dict></array><key>producers</key><array><dict><key>name</key><string></string></dict></array><key>codirectors</key><array><dict><key>name</key><string>codirector</string></dict></array><key>screenwriters</key><array><dict><key>name</key><string></string></dict></array></dict></plist> (edited)

According to Mike McCurdy, PMS does not check for empty strings.

**Comment by sandman4sure** [comment] 2015-07-07 10:51
I want to take a look at this, but the files are not available anymore.
Ismelda, care to share them again?
Thanks

**Comment by sandman4sure** [comment] 2015-07-07 17:34
There is an iTunMOVI tag in the file:

`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>studio</key><string>studio</string><key>cast</key><array><dict><key>name</key><string></string></dict></array><key>directors</key><array><dict><key>name</key><string></string></dict></array><key>producers</key><array><dict><key>name</key><string></string></dict></array><key>codirectors</key><array><dict><key>name</key><string>codirector</string></dict></array><key>screenwriters</key><array><dict><key>name</key><string></string></dict></array></dict></plist>`

I'll investigate what PMS does with this tag later

**Comment by sandman4sure** [comment] 2015-07-07 20:46
Fixed with this change:
`https://github.com/plexinc-agents/LocalMedia.bundle/commit/7850c6b94a45b307f49f2c9b1a3c5dd49ee5fd0e`

**Closed** 2015-07-07 21:34 UTC
